# run: conda env create --file environment.yml
name: helioknow

dependencies:
	- python=3.9
	- numpy
	- pandas
	- matplotlib
	- IPython
	- nbconvert=5.4.1
	- pip
	- pip:
	  - jupyter
	  - tika
	  - nltk
	  - datetime
